### ISSUE TITLE
Ryzen 7 5700g

### ISSUE THREAD

**Issue by Cicodevadatest** [GoedertDalmolin/EFI-X570-RYZEN-7-5700G-RX-6650-XT-HACKINTOSH#1]
Opa amigo, você conseguiria me ajudar a instalar no meu R7 5700g com uma RX 6600m?
Tô perdido nisso tentando fazer a alguns dias

**Comment by GoedertDalmolin** [comment]
Olá @Cicodevadatest, deixa seu discord ai ou alguma forma de contato.

Posteriormente eu entro em contato.

**Comment by Cicodevadatest** [comment]
Meu discord é "cicodevadahs"

**Comment by GoedertDalmolin** [comment]
A duvida era referente a outro hardware.

Alinhado via Discord.

Fechando este issue.
